import { storage } from "./storage";
import type { InsertProperty } from "@shared/schema";

// Seed data for development/testing when MLS Grid API is not configured
export async function seedData() {
  const sampleProperties: InsertProperty[] = [
    {
      id: "demo-property-001",
      listingId: "DEMO-001",
      mlgCanView: true,
      standardStatus: "Active",
      listPrice: "875000",
      unparsedAddress: "1234 Oak Street, Austin, TX 78701",
      streetNumber: "1234",
      streetName: "Oak Street",
      city: "Austin",
      stateOrProvince: "TX",
      postalCode: "78701",
      latitude: "30.2672",
      longitude: "-97.7431",
      bedroomsTotal: 4,
      bathroomsFull: 3,
      bathroomsHalf: 1,
      bathroomsTotalInteger: 4,
      livingArea: "3200",
      lotSizeSquareFeet: "8000",
      lotSizeAcres: "0.18",
      yearBuilt: 2018,
      propertyType: "Residential",
      propertySubType: "Single Family Residence",
      publicRemarks: "Stunning modern home in prime Austin location. Features open floor plan, gourmet kitchen with high-end appliances, master suite with spa-like bath, hardwood floors throughout, and beautiful landscaped backyard with pool.",
      daysOnMarket: 15,
      listingContractDate: new Date("2024-01-15"),
      modificationTimestamp: new Date(),
    },
    {
      id: "demo-property-002",
      listingId: "DEMO-002",
      mlgCanView: true,
      standardStatus: "Active",
      listPrice: "650000",
      unparsedAddress: "5678 Maple Avenue, Austin, TX 78704",
      streetNumber: "5678",
      streetName: "Maple Avenue",
      city: "Austin",
      stateOrProvince: "TX",
      postalCode: "78704",
      latitude: "30.2500",
      longitude: "-97.7500",
      bedroomsTotal: 3,
      bathroomsFull: 2,
      bathroomsHalf: 1,
      bathroomsTotalInteger: 3,
      livingArea: "2400",
      lotSizeSquareFeet: "6500",
      lotSizeAcres: "0.15",
      yearBuilt: 2015,
      propertyType: "Residential",
      propertySubType: "Single Family Residence",
      publicRemarks: "Charming home in desirable South Austin neighborhood. Updated kitchen, spacious bedrooms, large backyard perfect for entertaining. Close to parks, shopping, and restaurants.",
      daysOnMarket: 8,
      listingContractDate: new Date("2024-01-22"),
      modificationTimestamp: new Date(),
    },
    {
      id: "demo-property-003",
      listingId: "DEMO-003",
      mlgCanView: true,
      standardStatus: "Active Under Contract",
      listPrice: "725000",
      unparsedAddress: "910 Pine Drive, Austin, TX 78701",
      streetNumber: "910",
      streetName: "Pine Drive",
      city: "Austin",
      stateOrProvince: "TX",
      postalCode: "78701",
      latitude: "30.2700",
      longitude: "-97.7450",
      bedroomsTotal: 4,
      bathroomsFull: 2,
      bathroomsHalf: 1,
      bathroomsTotalInteger: 3,
      livingArea: "2800",
      lotSizeSquareFeet: "7200",
      lotSizeAcres: "0.17",
      yearBuilt: 2016,
      propertyType: "Residential",
      propertySubType: "Single Family Residence",
      publicRemarks: "Beautiful home with modern finishes throughout. Open concept living/dining, chef's kitchen, spacious bedrooms, and covered patio. Walking distance to downtown.",
      daysOnMarket: 5,
      listingContractDate: new Date("2024-01-25"),
      modificationTimestamp: new Date(),
    },
    {
      id: "demo-property-004",
      listingId: "DEMO-004",
      mlgCanView: true,
      standardStatus: "Active",
      listPrice: "950000",
      unparsedAddress: "2345 Cedar Lane, Austin, TX 78703",
      streetNumber: "2345",
      streetName: "Cedar Lane",
      city: "Austin",
      stateOrProvince: "TX",
      postalCode: "78703",
      latitude: "30.2900",
      longitude: "-97.7600",
      bedroomsTotal: 5,
      bathroomsFull: 4,
      bathroomsHalf: 1,
      bathroomsTotalInteger: 5,
      livingArea: "3800",
      lotSizeSquareFeet: "10000",
      lotSizeAcres: "0.23",
      yearBuilt: 2020,
      propertyType: "Residential",
      propertySubType: "Single Family Residence",
      publicRemarks: "Luxurious custom home in prestigious Tarrytown. High-end finishes, gourmet kitchen, wine cellar, home theater, pool with spa, and gorgeous hill country views.",
      daysOnMarket: 22,
      listingContractDate: new Date("2024-01-08"),
      modificationTimestamp: new Date(),
    },
    {
      id: "demo-property-005",
      listingId: "DEMO-005",
      mlgCanView: true,
      standardStatus: "Closed",
      listPrice: "580000",
      unparsedAddress: "7890 Elm Street, Austin, TX 78704",
      streetNumber: "7890",
      streetName: "Elm Street",
      city: "Austin",
      stateOrProvince: "TX",
      postalCode: "78704",
      latitude: "30.2450",
      longitude: "-97.7480",
      bedroomsTotal: 3,
      bathroomsFull: 2,
      bathroomsHalf: 0,
      bathroomsTotalInteger: 2,
      livingArea: "2100",
      lotSizeSquareFeet: "5500",
      lotSizeAcres: "0.13",
      yearBuilt: 2012,
      propertyType: "Residential",
      propertySubType: "Single Family Residence",
      publicRemarks: "Well-maintained home in established neighborhood. Updated throughout, large living areas, private backyard, and excellent Austin ISD schools.",
      daysOnMarket: 12,
      listingContractDate: new Date("2024-01-05"),
      modificationTimestamp: new Date(),
    },
    {
      id: "demo-property-006",
      listingId: "DEMO-006",
      mlgCanView: true,
      standardStatus: "Active",
      listPrice: "1150000",
      unparsedAddress: "456 Willow Way, Austin, TX 78746",
      streetNumber: "456",
      streetName: "Willow Way",
      city: "Austin",
      stateOrProvince: "TX",
      postalCode: "78746",
      latitude: "30.2350",
      longitude: "-97.8000",
      bedroomsTotal: 5,
      bathroomsFull: 5,
      bathroomsHalf: 2,
      bathroomsTotalInteger: 7,
      livingArea: "4500",
      lotSizeSquareFeet: "15000",
      lotSizeAcres: "0.34",
      yearBuilt: 2021,
      propertyType: "Residential",
      propertySubType: "Single Family Residence",
      publicRemarks: "Stunning contemporary masterpiece in exclusive West Austin. Floor-to-ceiling windows, chef's kitchen, master retreat, home office, infinity pool, outdoor kitchen, and breathtaking lake views.",
      daysOnMarket: 30,
      listingContractDate: new Date("2024-01-01"),
      modificationTimestamp: new Date(),
    },
  ];

  for (const property of sampleProperties) {
    try {
      const existing = await storage.getPropertyByListingId(property.listingId);
      if (!existing) {
        await storage.createProperty(property);
      }
    } catch (error) {
      console.error("Failed to seed property:", error);
    }
  }

  const count = await storage.getAllProperties();
  console.log(`✅ Seeded sample properties for development (${count.length} total)`);
}
